### ISSUE TITLE
require -> require_once in index-zlrouter.php

### ISSUE THREAD

**Issue by HenkPoley** [courtesysoft/zerolith-preview#3]
I'm not quite sure if index-zlrouter.php is meant to be used as an index page, e.g. open it as http://zerolith-preview.test/index-zlrouter.php in a browser from a local Laragon webserver.

But I'm seeing a issue with including this same file again. And it's resolved by changing:

```php
if($allowDirect && strpos(strtolower($origurl), ".php")) //direct hit
{ zl_router_cwd($origurl); require(substr($origurl, 1)); exit; }
```

to 

```php
if($allowDirect && strpos(strtolower($origurl), ".php")) //direct hit
{ zl_router_cwd($origurl); require_once(substr($origurl, 1)); exit; }
```

The processing time it notes is often <1ms, which is quite fast for PHP, coming from Laravel (75-255-700ms 😭 ).

**Comment by courtesysoft** [comment]
Hi, i'm sorry this isn't documented at all and confusing AF. I appreciate you letting me know about this.
This part of the system has been written, tested, but not used in production yet.

I have updated the file with comments to explain what it is and how to use it.
require_once shouldn't be necessary when it is 'used as directed' :)

Yeah, Zerolith is ~50x less internally complex than laravel/symfony. no surprise the performance blows your socks off :)
